version: '3.8'

services:
  tumsexy:
    image: ghcr.io/tum-dev/tum.sexy/sexy-server:latest
    restart: unless-stopped
    networks:
      - traefik_traefik

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tumsexy.entrypoints=webs"
      - "traefik.http.routers.tumsexy.tls.domains[0].main=tum.sexy"
      - "traefik.http.routers.tumsexy.tls.domains[0].sans=*.tum.sexy"
      - "traefik.http.routers.tumsexy.tls.certresolver=sexyresolver"
      - "traefik.http.routers.tumsexy.rule=Host(`tum.sexy`) || HostRegexp(`tum.sexy`, `{subdomain:[a-z0-9\\-]+}.tum.sexy`)"
      - "traefik.http.services.tumsexy.loadbalancer.server.port=80"
    healthcheck:
      test: wget -q --spider http://localhost:80/img/pin-material.svg
      retries: 5
      start_period: 10s

networks:
  traefik_traefik:
    external: true
